# Generated by Django 2.1.2 on 2018-10-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0002_auto_20181007_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'recurso', 'verbose_name_plural': 'recursos'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name_plural': 'tipos'},
        ),
    ]
