# Generated by Django 2.1.2 on 2018-10-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0003_auto_20181010_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='planproduccion',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='planproduccion',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='SGRD.Recurso'),
        ),
    ]
