# Generated by Django 2.1.2 on 2018-10-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0004_auto_20181011_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planproduccion',
            name='descripcion',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
