# Generated by Django 2.1.2 on 2018-10-12 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0005_auto_20181011_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planproduccion',
            name='recurso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='SGRD.Recurso'),
        ),
    ]
