# Generated by Django 2.1.2 on 2018-10-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0007_auto_20181022_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(default='79ADDC', max_length=6),
        ),
    ]
