# Generated by Django 2.1.2 on 2018-11-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0009_clip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'ordering': ['-inicio_produccion'], 'verbose_name': 'recurso', 'verbose_name_plural': 'recursos'},
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='ruta_compartida',
        ),
        migrations.AddField(
            model_name='recurso',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fin_elaboracion_recurso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='inicio_produccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
