# Generated by Django 2.1.2 on 2018-11-02 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0010_auto_20181102_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='inicio_produccion',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
