# Generated by Django 2.1.2 on 2018-11-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0011_auto_20181102_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='SGRD.Archivo'),
        ),
    ]
