# Generated by Django 2.1.2 on 2018-11-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0011_auto_20181102_0436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradaplan',
            options={'ordering': ['-dia']},
        ),
    ]
