# Generated by Django 2.1.2 on 2018-11-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0012_auto_20181103_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='SGRD.Etiqueta'),
        ),
    ]
