# Generated by Django 2.1.2 on 2018-11-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0012_auto_20181103_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradaplan',
            options={'ordering': ['dia']},
        ),
    ]
