# Generated by Django 2.1.2 on 2018-11-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0014_clip_etiquetas'),
        ('SGRD', '0013_auto_20181103_0456'),
    ]

    operations = [
    ]
