# Generated by Django 2.1.3 on 2018-11-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0016_auto_20181112_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(default='#79ADDC', max_length=7),
        ),
    ]
