# Generated by Django 2.1.3 on 2018-11-18 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0016_auto_20181112_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescargarArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateField(blank=True, default=datetime.datetime.now)),
                ('hora_descarga', models.TimeField(default=datetime.datetime(2018, 11, 18, 23, 9, 6, 658197))),
                ('archivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SGRD.Archivo')),
            ],
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(default='#79ADDC', max_length=7),
        ),
    ]
