# Generated by Django 2.1.3 on 2018-11-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0017_auto_20181121_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
