# Generated by Django 2.1.3 on 2018-11-18 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0017_auto_20181118_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargararchivo',
            name='hora_descarga',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
