# Generated by Django 2.1.3 on 2018-11-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0018_auto_20181118_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descargararchivo',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivo',
            name='descarga_archivo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGRD.DescargarArchivo'),
        ),
    ]
