# Generated by Django 2.1.3 on 2018-11-24 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGRD', '0023_auto_20181123_1428'),
        ('SGRD', '0018_archivo_terminado'),
    ]

    operations = [
    ]
